spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: micro-product
  main:
    allow-bean-definition-overriding: true  
server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  endpoints:
    web:
      exposure:
        include: refresh,actuator,health,metrics,info
security:
  oauth2:
    client:
      clientId: ${AUTH_CLIENT_ID:web}
      clientSecret: ${AUTH_CLIENT_SECRET:pass}
      grant-type: ${AUTH_CLIENT_CREDENTIALS:client_credentials}
      scope: server
      access-token-uri: ${AUTH_SERVICE_URL:http://localhost}:${AUTH_SERVICE_PORT:8090}/oauth/token
    resource:
      token-info-uri: ${AUTH_SERVICE_URL:http://localhost}:${AUTH_SERVICE_PORT:8090}/oauth/check_token
